# This is the configuration file for the application.
# It specifies built-in Harper components that will load the specified feature and files.
# For more information, see https://docs.harperdb.io/docs/developers/components/built-in

# This provides the HTTP REST interface for all exported resources
rest: true

# These reads GraphQL schemas to define the schema of database/tables/attributes.
graphqlSchema:
  files: 'schema.graphql'
jsResource:
  files: 'resources.js'
